/*
 * Author: AndroPlus-org <hosigumayuugi@gmail.com>
 */

let trans_ja = {
    // app
    'Menu': 'メニュー',
    'Home': 'ホーム',
    'Setting': '設定',
    'Switching APP to new version.': 'アプリを新バージョンに切替中',

    // home
    'Projects': 'プロジェクト',
    'Open': '開く',
    'New': '新規',
    'Print': '印刷',
    'Edit': '編集',
    'Duplicate': '複製',
    'Export': 'エクスポート',
    'Export (Secret)': '保護してエクスポート',
    'Delete': '削除',
    'Cancel': 'キャンセル',

    'Alert': '注意',
    "Can't export secret project as normal.": '保護されたプロジェクトを通常版としてはエクスポートできません',
    'OK': 'OK',
    'Format error': '形式エラー',
    'Import succeeded': 'インポート完了しました',

    // edit
    'Add Image': '画像を追加',
    'Add Text': '文字を追加',
    'User Fonts': 'ユーザーフォント',
    'Ratio 1:1': '比率 1:1',
    'Delete Item': 'アイテムを削除',
    'Move up': '上に移動',
    'Down': '下に移動',
    'Top': '最前面',
    'Bottom': '最背面',
    'Group': 'グループ',
    'Ungroup': 'グループ化解除',
    'Save': '保存',
    'Print Preview': '印刷プレビュー',
    'Opacity': '不透明度',
    'Add Font': 'フォントを追加',
    'Add Text': '文字を追加',
    'Font': 'フォント',
    'Fallback Font': 'フォールバックフォント',
    'Size': 'サイズ',
    'Style': 'スタイル',
    'Normal': '通常',
    'Bold': '太字',
    'Italic': 'イタリック',
    'Align': '配置',
    'Left': '左寄せ',
    'Center': '中央寄せ',
    'Right': '右寄せ',
    'Color': '色',
    'Shadow': '影',
    'Blur': 'ぼかし',
    'Save succeeded': '保存しました',
    'At least select two items': '2つ以上のアイテムを選んでください',
    'Not a group': 'グループではありません',
    'Enter text here...': 'ここに文字を入力...',

    // crop
    'Crop': 'クロップ',
    'Dup..': '複製',
    'Del': '削除',
    'Re-Edit': '再編集',
    'Combine Crops': 'クロップを結合',
    'Density': '濃度',
    'Brightness': '明るさ',
    'Saturation': '彩度',
    'Start': '開始',
    'Please select one crop first.': 'クロップをまず選択してください',
    'Get crop data error.': 'クロップデータの取得エラー',
    'Loading, please try later.': '読み込み中、後でお試しください',
    'Upload prepare failed.': 'アップロード準備に失敗しました',
    'Upload done, sync failed.': 'アップロード完了、動機に失敗しました',
    'Convert': '変換',
    'Send': '送信',
    'Upload succeeded': '成功しました',

    // setting
    'Global Density': '濃度',
    'Color Calibration': '色のキャリブレーション',
    'Direction': '向き',
    'Cartridge Type': 'カートリッジの種類',
    'CMY': 'CMY',
    'CYM': 'CYM',
    'Display Unit': '表示単位',
    'Display Grid': '表示格子',
    'Device Setting': '機器設定',
    'Drive Strength': 'ドライブ強度',
    'Color Alignment': '色の調整',
    'Leading Space': '先頭の空白',
    'Buzzer': '音を鳴らす',
    'Default': 'デフォルト',
    'Configuration': '設定',
    'SSID': 'SSID',
    'Password': 'パスワード',
    'Channel': 'チャンネル',
    'Not allowed in the US': 'アメリカでは許可されていません',
    'Japan only': '日本のみ',
    'Read Dev': '読み込み',
    'Write Dev': '書き込み',
    'Device Info': '機器情報',
    'APP Version': 'アプリバージョン',
    'FW Version': 'ファームウェアバージョン',
    'DEV ID': '機器 ID',
    'Sensor IQC': 'センサー IQC',
    'Certificate': '証明書',
    'Link': 'リンク',
    'Firmware Update': 'ファームウェア更新',
    'Last Firmware': '最新のファームウェア',
    'Refresh App': 'アプリの再読み込み',
    'Read app_conf from device error': '機器からの app_conf の読み込みエラー',
    'Read conf from device error': '機器からの conf の読み込みエラー',
    'Write conf to device error': '機器への conf の書き込みエラー',
    'Write app_conf to device error': '機器への app_conf の書き込みエラー',
    'Write to device succeeded': '機器へ書き込みました',
    'Read wifi conf from device error': '機器からの Wi-Fi 設定の読み込みエラー',
    'SSID is empty!': 'SSID が空です！',
    'Passwd at least 8 char!': 'パスワードは最低8文字です！',
    'Write wifi conf to device error': '機器への Wi-Fi 設定の書き込みエラー',
    'Write to device succeeded, reboot...': '書き込みました。再起動します...',
    'Please select file first': 'ファイルを選んでください',
    'Upgrade succeeded, reboot...': '更新しました。再起動します...',
    'Upgrade failed': '更新に失敗しました',
    'Upload': 'アップロード',

    // other
    'Err': 'エラー',
    'No space left': '空きがありません'
};

export { trans_ja };
