
let trans_ko = {
    // app
    'Menu': '메뉴',
    'Home': '홈',
    'Setting': '설정',
    'Switching APP to new version.': '앱 을 새버전으로 전환',

    // home
    'Projects': '프로젝트',
    'Open': '열기',
    'New': '새로 만들기',
    'Print': '프린트',
    'Edit': '편집',
    'Duplicate': '복제',
    'Export': '내보내기',
    'Export (Secret)': '내보내기 (보호)',
    'Delete': '삭제',
    'Cancel': '취소',

    'Alert': '경보',
    "Can't export secret project as normal.": '시크릿 프로젝트를 정상적으로 내보낼 수 없습니다',
    'OK': '확인',
    'Format error': '포맷 오류',
    'Import succeeded': '가져오기 완료',

    // edit
    'Add Image': '이미지 추가',
    'Add Text': '텍스트 추가',
    'User Fonts': '사용자 글꼴',
    'Ratio 1:1': '1:1비율',
    'Delete Item': '항목 삭제',
    'Move up': '위로 이동',
    'Down': '아래',
    'Top': '상단',
    'Bottom': '하단',
    'Group': '그룹',
    'Ungroup': '그룹 해제',
    'Save': '저장',
    'Print Preview': '인쇄 미리보기',
    'Opacity': '투명도',
    'Add Font': '폰트 추가',
    'Add Text': '텍스트 추가',
    'Font': '글꼴',
    'Fallback Font': '대체 글꼴',
    'Size': '크기',
    'Style': '스타일',
    'Normal': '일반',
    'Bold': '굵음',
    'Italic': '기울임',
    'Align': '정렬',
    'Left': '왼쪽',
    'Center': '가운데',
    'Right': '오른쪽',
    'Color': '색깔',
    'Shadow': '그림자',
    'Blur': '흐림',
    'Save succeeded': '저장 성공',
    'At least select two items': '최소 두 항목을 선택하세요',
    'Not a group': '그룹이 아닙니다',
    'Enter text here...': '여기에 텍스트를 입력하십시오...',

    // crop
    'Crop': '자르기',
    'Dup..': '복제',
    'Del': '삭제',
    'Re-Edit': '다시 편집',
    'Combine Crops': '자른 이미지 결합',
    'Density': '밀도',
    'Brightness': '밝기',
    'Saturation': '채도',
    'Start': '시작',
    'Please select one crop first.': '먼저 자른 이미지를 선택하세요',
    'Get crop data error.': '자른 이미지 데이터를 가져오지 못했습니다',
    'Loading, please try later.': '로딩중, 잠시후 다시 시도해주세요.',
    'Upload prepare failed.': '업로드 준비에 실패했습니다.',
    'Upload done, sync failed.': '업로드 완료, 동기화 실패',
    'Convert': '변환',
    'Send': '보내기',
    'Upload succeeded': '성공',

    // setting
    'Global Density': '농도',
    'Color Calibration': '색 보정',
    'Cyan': '청록',
    'Magenta': '마젠타',
    'Yellow': '노랑',
    'Direction': '방향',
    'Cartridge Type': '카트리지 유형',
    'CMY': 'CMY',
    'CYM': 'CYM',
    'Display Unit': '디스플레이 단위',
    'Display Grid': '디스플레이 그리드',
    'Device Setting': '기기 설정',
    'Drive Strength': '추진력',
    'Color Alignment': '색상 조정',
    'Leading Space': '선행 공백',
    'Buzzer': '버저',
    'Default': '기본',
    'Configuration': '구성',
    'SSID': 'SSID',
    'Password': '비밀번호',
    'Channel': '채널',
    'Not allowed in the US': '미국에서는 허용되지 않습니다',
    'Japan only': '일본만',
    'Read Dev': '설정읽기',
    'Write Dev': '설정쓰기',
    'Device Info': '기기 정보',
    'APP Version': '앱 버전',
    'FW Version': '펌웨어 버전',
    'DEV ID': '기기 ID',
    'Sensor IQC': '센서 IQC',
    'Certificate': '증명서',
    'Link': '링크',
    'Firmware Update': '펌웨어 업데이트',
    'Last Firmware': '최신 펌웨어',
    'Refresh App': '앱 새로 고침',
    'Read app_conf from device error': '기기에서 app_conf 로드 오류',
    'Read conf from device error': '기기에서 conf 로드 오류',
    'Write conf to device error': '기기에서 conf 쓰기 오류',
    'Write app_conf to device error': '기기에서 app_conf 쓰기 오류',
    'Write to device succeeded': '장치에 쓰기 성공',
    'Read wifi conf from device error': '기기에서 Wi-Fi 설정 로드 오류',
    'SSID is empty!': 'SSID가 비어 있습니다!',
    'Passwd at least 8 char!': '비밀번호는 최소8자 입니다!',
    'Write wifi conf to device error': '기기에 Wi-Fi 설정 쓰기 오류',
    'Write to device succeeded, reboot...': '장치에 쓰기 성공, 다시 시작합니다...',
    'Please select file first': '파일을 선택하세요',
    'Upgrade succeeded, reboot...': '업데이트했습니다, 다시 시작합니다...',
    'Upgrade failed': '업그레이드 실패',
    'Upload': '업로드',

    // other
    'Err': '오류',
    'No space left': '남은 공간이 없습니다'
};

export { trans_ko };
