/*
 * Copyright (c) 2019, Kudo, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

// cat zh_hk.js | cconv -f UTF8 -t UTF8-CN
let trans_zh_cn = {
    // app
    'Menu': '菜单',
    'Home': '主页',
    'Setting': '设置',
    'Switching APP to new version.': '切换 APP 至新版本',

    // home
    'Projects': '项目',
    'Open': '打开',
    'New': '新建',
    'Print': '打印',
    'Edit': '编辑',
    'Duplicate': '重复',
    'Export': '导出',
    'Export (Secret)': '导出（保密）',
    'Delete': '删除',
    'Cancel': '取消',

    'Alert': '警告',
    "Can't export secret project as normal.": '保密项目不可以普通导出',
    'OK': '确定',
    'Format error': '格式错误',
    'Import succeeded': '导入成功',

    // edit
    'Add Image': '添加图片',
    'Add Text': '添加文字',
    'User Fonts': '用户字形',
    'Ratio 1:1': '比例 1:1',
    'Delete Item': '删除选中',
    'Move up': '移上',
    'Down': '移下',
    'Top': '置顶',
    'Bottom': '置底',
    'Group': '组合',
    'Ungroup': '拆散',
    'Save': '保存',
    'Print Preview': '打印预览',
    'Opacity': '透明度',
    'Add Font': '添加字形',
    'Add Text': '添加文字',
    'Font': '字形',
    'Fallback Font': '后备字形',
    'Size': '大小',
    'Style': '风格',
    'Normal': '普通',
    'Bold': '粗体',
    'Italic': '斜体',
    'Align': '对齐',
    'Left': '左',
    'Center': '中',
    'Right': '右',
    'Color': '颜色',
    'Shadow': '阴影',
    'Blur': '模糊',
    'Invalid font file!': '无效字体文件！',
    'Save succeeded': '保存成功',
    'At least select two items': '最少需要选中两项',
    'Not a group': '不是一个组合',
    'Enter text here...': '在此输入文字...',

    // crop
    'Crop': '裁选',
    'New': '新建',
    'Dup..': '重复',
    'Del': '删除',
    'Re-Edit': '回到编辑',
    'Combine Crops': '合并裁选',
    'Density': '浓度',
    'Brightness': '亮度',
    'Saturation': '饱和度',
    'Start': '开始',
    'Please select one crop first.': '请先选择裁选框',
    'Get crop data error.': '获取裁选数据失败',
    'Loading, please try later.': '正在加载，请稍后再试',
    'Upload prepare failed.': '上传準备失败',
    'Upload done, sync failed.': '上传完成，同步出错',
    'Convert': '转换',
    'Send': '发送',
    'Upload succeeded': '成功',

    // setting
    'Global Density': '全局浓度',
    'Color Calibration': '色彩校準',
    'Cyan': '青色',
    'Magenta': '品红',
    'Yellow': '黄色',
    'Direction': '方向',
    'Cartridge Type': '墨盒类型',
    'CMY': '青红黄',
    'CYM': '青黄红',
    'Display Unit': '显示单位',
    'Display Grid': '显示网格',
    'Device Setting': '设备设置',
    'Drive Strength': '驱动强度',
    'Color Alignment': '颜色对齐',
    'Leading Space': '前置空白',
    'Buzzer': '蜂鸣器',
    'Default': '默认',
    'Configuration': '配置',
    'SSID': 'SSID 名称',
    'Password': '密码',
    'Channel': '通道',
    'Not allowed in the US': '不可在美国使用',
    'Japan only': '仅限日本',
    'Read Dev': '读设备',
    'Write Dev': '写设备',
    'Device Info': '设备信息',
    'APP Version': 'APP 版本',
    'FW Version': '固件 版本',
    'DEV ID': '设备 ID',
    'Sensor IQC': '传感器 IQC',
    'Certificate': '证书',
    'Link': '链接',
    'Firmware Update': '固件升级',
    'Last Firmware': '最新固件',
    'Refresh App': '刷新应用',
    'Read app_conf from device error': '读取 app_conf 出错',
    'Read conf from device error': '读取 conf 出错',
    'Write conf to device error': '写 conf 出错',
    'Write app_conf to device error': '写 app_conf 出错',
    'Write to device succeeded': '写入成功',
    'Read wifi conf from device error': '读取 Wi-Fi 配置出错',
    'SSID is empty!': 'SSID 不能为空！',
    'Passwd at least 8 char!': '密码最短 8 位！',
    'Write wifi conf to device error': '写 Wi-Fi 配置出错',
    'Write to device succeeded, reboot...': '写入成功，重启...',
    'Please select file first': '请先选择文件',
    'Upgrade succeeded, reboot...': '升级成功，重启...',
    'Upgrade failed': '升级失败',
    'Upload': '上传',

    // other
    'Err': '出错',
    'No space left': '无剩余空间'
};

export { trans_zh_cn };
