/*
 * Copyright (c) 2019, Kudo, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

let trans_zh_hk = {
    // app
    'Menu': '菜單',
    'Home': '主頁',
    'Setting': '設置',
    'Switching APP to new version.': '切換 APP 至新版本',

    // home
    'Projects': '項目',
    'Open': '打開',
    'New': '新建',
    'Print': '打印',
    'Edit': '編輯',
    'Duplicate': '重複',
    'Export': '導出',
    'Export (Secret)': '導出（保密）',
    'Delete': '刪除',
    'Cancel': '取消',

    'Alert': '警告',
    "Can't export secret project as normal.": '保密項目不可以普通導出',
    'OK': '確定',
    'Format error': '格式錯誤',
    'Import successed': '導入成功',

    // edit
    'Add Image': '添加圖片',
    'Add Text': '添加文字',
    'User Fonts': '用戶字形',
    'Ratio 1:1': '比例 1:1',
    'Delete Item': '刪除選中',
    'Move up': '移上',
    'Down': '移下',
    'Top': '置頂',
    'Bottom': '置底',
    'Group': '組合',
    'Ungroup': '拆散',
    'Save': '保存',
    'Print Preview': '打印預覽',
    'Opacity': '透明度',
    'Add Font': '添加字形',
    'Add Text': '添加文字',
    'Font': '字形',
    'Fallback Font': '後備字形',
    'Size': '大小',
    'Style': '風格',
    'Normal': '普通',
    'Bold': '粗體',
    'Italic': '斜體',
    'Align': '對齊',
    'Left': '左',
    'Center': '中',
    'Right': '右',
    'Color': '顏色',
    'Shadow': '陰影',
    'Blur': '模糊',
    'Invalid font file!': '無效字形文件！',
    'Save successed': '保存成功',
    'At least select two items': '最少需要選中兩項',
    'Not a group': '不是一個組合',
    'Enter text here...': '在此輸入文字...',

    // crop
    'Crop': '裁選',
    'New': '新建',
    'Dup..': '重複',
    'Del': '刪除',
    'Re-Edit': '回到編輯',
    'Combine Crops': '合併裁選',
    'Density': '濃度',
    'Brightness': '亮度',
    'Saturation': '飽和度',
    'Start': '開始',
    'Please select one crop first.': '請先選擇裁選框',
    'Get crop data error.': '獲取裁選數據失敗',
    'Loading, please try later.': '正在加載，請稍後再試',
    'Upload prepare failed.': '上傳準備失敗',
    'Upload done, sync failed.': '上傳完成，同步出錯',
    'Convert': '轉換',
    'Send': '發送',
    'Successed': '成功',

    // setting
    'Global Density': '全局浓度',
    'Color Calibration': '色彩校準',
    'Cyan': '青色',
    'Magenta': '品紅',
    'Yellow': '黃色',
    'Direction': '方向',
    'Cartridge Type': '墨盒類型',
    'CMY': '青紅黃',
    'CYM': '青黃紅',
    'Display Unit': '顯示單位',
    'Display Grid': '顯示網格',
    'Device Setting': '設備設置',
    'Drive Strength': '驅動強度',
    'Color Alignment': '顏色對齊',
    'Leading Space': '前置空白',
    'Buzzer': '蜂鳴器',
    'Default': '默認',
    'Configuration': '配置',
    'SSID': 'SSID 名稱',
    'Password': '密碼',
    'Channel': '通道',
    'Not allowed in the US': '不可在美國使用',
    'Japan only': '僅限日本',
    'Read Dev': '讀設備',
    'Write Dev': '寫設備',
    'Device Info': '設備信息',
    'APP Version': 'APP 版本',
    'FW Version': '固件 版本',
    'DEV ID': '設備 ID',
    'Sensor IQC': '傳感器 IQC',
    'Certificate': '證書',
    'Link': '鏈接',
    'Firmware Update': '固件升級',
    'Last Firmware': '最新固件',
    'Refresh App': '刷新應用',
    'Read app_conf from device error': '讀取 app_conf 出錯',
    'Read conf from device error': '讀取 conf 出錯',
    'Write conf to device error': '寫 conf 出錯',
    'Write app_conf to device error': '寫 app_conf 出錯',
    'Write to device successed': '寫入成功',
    'Read wifi conf from device error': '讀取 Wi-Fi 配置出錯',
    'SSID is empty!': 'SSID 不能爲空！',
    'Passwd at least 8 char!': '密碼最短 8 位！',
    'Write wifi conf to device error': '寫 Wi-Fi 配置出錯',
    'Write to device successed, reboot...': '寫入成功，重啓...',
    'Please select file first': '請先選擇文件',
    'Upgrade successed, reboot...': '升級成功，重啓...',
    'Upgrade failed': '升級失敗',
    'Upload': '上傳',

    // other
    'Err': '出錯',
    'No space left': '無剩餘空間'
};

export { trans_zh_hk };
