#! /bin/sh
#

echo "MB: $0 $1"
[ "$1" != "start" ] && exit
cd /opt

ubiattach /dev/ubi_ctrl -m 3
mount -t ubifs ubi1:data /root

if [ $? -ne 0 ] || [ ! -f /root/mb_etc/S80mb ]; then
    echo "MB: factory resetting ..."
    umount /root
    ubidetach -m 3
    ubiformat /dev/mtd3
    ubiattach /dev/ubi_ctrl -m 3
    ubimkvol /dev/ubi1 -N data -m
    mount -t ubifs ubi1:data /root || { echo "MB: flash error"; exit; }
    busybox tar xf *-fw-*.tar -C /root --strip 1 --exclude */run.sh
    flash_erase /dev/mtd1 0 32
    nandwrite -m -p /dev/mtd1 /root/uImage
    rm /root/uImage
    sync
fi

echo "MB: start app ..."
/root/mb_etc/S80mb start

