#! /bin/sh
#

rm -rf /dev/null 
mknod /dev/null c 1 3 
chmod 666 /dev/null

mv /dev/random /dev/random_bk
ln -sf /dev/urandom /dev/random


rm -f /etc/udhcpd.conf /etc/wpa_supplicant.conf
mv /etc/init.d/S41dhcpcd /etc/init.d/._S41dhcpcd
mv /etc/init.d/S50stunnel /etc/init.d/._S50stunnel
mv /etc/init.d/S50radvd /etc/init.d/._S50radvd
ln -sf /root/mb_etc/S80mb /etc/init.d/S80mb
rm -f /etc/init.d/S01init

#reboot
sync
echo b > /proc/sysrq-trigger

