/*
 * Copyright (c) 2019, Kudo, Inc.
 * All rights reserved.
 *
 * Author: Duke Fong <d@d-l.io>
 */

let trans_hk = {
    // app
    'Menu': '菜單',
    'Home': '主頁',
    'Setting': '設置',
    'Switching APP to new version.': '切換 APP 至新版本',
    
    // home
    'Projects': '項目',
    'Open': '打開',
    'New': '新建',
    'Print': '打印',
    'Edit': '編輯',
    'Duplicate': '重複',
    'Export': '導出',
    'Export (Secret)': '導出（保密）',
    'Delete': '刪除',
    'Cancel': '取消',
    
    'Alert': '警告',
    "Can't export secret project as normal.": '保密項目不可以普通導出',
    'OK': '確定',
    'Format error': '格式錯誤',
    'Import successed': '導入成功',
    
    // edit
    'Add Image': '添加圖片',
    'Add Text': '添加文字',
    'User Fonts': '用戶字形',
    'Ratio 1:1': '比例 1:1',
    'Delete Item': '刪除選中',
    'Move up': '移上',
    'Down': '移下',
    'Top': '置頂',
    'Bottom': '置底',
    'Group': '組合',
    'Ungroup': '拆散',
    'Save': '保存',
    'Print Preview': '打印預覽',
    'Opacity': '透明度',
    'Add Font': '添加字形',
    'Add Text': '添加文字',
    'Font': '字形',
    'Fallback Font': '後備字形',
    'Size': '大小',
    'Style': '風格',
    'Normal': '普通',
    'Bold': '粗體',
    'Italic': '斜體',
    'Align': '對齊',
    'Left': '左',
    'Center': '中',
    'Right': '右',
    'Color': '顏色',
    'Shadow': '陰影',
    'Blur': '模糊',
    'Save successed': '保存成功',
    'At least select two items': '最少需要選中兩項',
    'Not a group': '不是一個組合',
    'Enter text here...': '在此輸入文字...',
    
    // crop
    'Crop': '裁選',
    'New': '新建',
    'Dup..': '重複',
    'Del': '刪除',
    'Re-Edit': '回到編輯',
    'Combine Crops': '合併裁選',
    'Density': '濃度',
    'Brightness': '亮度',
    'Saturation': '飽和度',
    'Start': '開始',
    'Please select one crop first.': '請先選擇裁選框',
    'Get crop data error.': '獲取裁選數據失敗',
    'Loading, please try later.': '正在加載，請稍後再試',
    'Upload prepare failed.': '上傳準備失敗',
    'Upload done, sync failed.': '上傳完成，同步出錯',
    'Convert': '轉換',
    'Send': '發送',
    'Successed': '成功',
    
    // setting
    'Global Density': '全局浓度',
    'Color Calibration': '色彩校準',
    'Cyan': '青色',
    'Magenta': '品紅',
    'Yellow': '黃色',
    'Direction': '方向',
    'Cartridge Type': '墨盒類型',
    'CMY': '青紅黃',
    'CYM': '青黃紅',
    'Display Unit': '顯示單位',
    'Device Setting': '設備設置',
    'Drive Strength': '驅動強度',
    'Color Alignment': '顏色對齊',
    'Leading Space': '前置空白',
    'Buzzer': '蜂鳴器',
    'Default': '默認',
    'Configuration': '配置',
    'SSID': 'SSID 名稱',
    'Password': '密碼',
    'Channel': '通道',
    'Not allowed in the US': '不可在美國使用',
    'Japan only': '僅限日本',
    'Read Dev': '讀設備',
    'Write Dev': '寫設備',
    'Device Info': '設備信息',
    'APP Version': 'APP 版本',
    'FW Version': '固件 版本',
    'DEV ID': '設備 ID',
    'Sensor IQC': '傳感器 IQC',
    'Certificate': '證書',
    'Link': '鏈接',
    'Firmware Update': '固件升級',
    'Last Firmware': '最新固件',
    'Refresh App': '刷新應用',
    'Read app_conf from device error': '讀取 app_conf 出錯',
    'Read conf from device error': '讀取 conf 出錯',
    'Write conf to device error': '寫 conf 出錯',
    'Write app_conf to device error': '寫 app_conf 出錯',
    'Write to device successed': '寫入成功',
    'Read wifi conf from device error': '讀取 Wi-Fi 配置出錯',
    'SSID is empty!': 'SSID 不能爲空！',
    'Passwd at least 8 char!': '密碼最短 8 位！',
    'Write wifi conf to device error': '寫 Wi-Fi 配置出錯',
    'Write to device successed, reboot...': '寫入成功，重啓...',
    'Please select file first': '請先選擇文件',
    'Upgrade successed, reboot...': '升級成功，重啓...',
    'Upgrade failed': '升級失敗',
    'Upload': '上傳',
    
    // other
    'Err': '出錯',
    'No space left': '無剩餘空間'
};

// cat lang.js | cconv -f UTF8 -t UTF8-CN
let trans_cn = {
    // app
    'Menu': '菜单',
    'Home': '主页',
    'Setting': '设置',
    'Switching APP to new version.': '切换 APP 至新版本',
    
    // home
    'Projects': '项目',
    'Open': '打开',
    'New': '新建',
    'Print': '打印',
    'Edit': '编辑',
    'Duplicate': '重复',
    'Export': '导出',
    'Export (Secret)': '导出（保密）',
    'Delete': '删除',
    'Cancel': '取消',
    
    'Alert': '警告',
    "Can't export secret project as normal.": '保密项目不可以普通导出',
    'OK': '确定',
    'Format error': '格式错误',
    'Import successed': '导入成功',
    
    // edit
    'Add Image': '添加图片',
    'Add Text': '添加文字',
    'User Fonts': '用户字形',
    'Ratio 1:1': '比例 1:1',
    'Delete Item': '删除选中',
    'Move up': '移上',
    'Down': '移下',
    'Top': '置顶',
    'Bottom': '置底',
    'Group': '组合',
    'Ungroup': '拆散',
    'Save': '保存',
    'Print Preview': '打印预览',
    'Opacity': '透明度',
    'Add Font': '添加字形',
    'Add Text': '添加文字',
    'Font': '字形',
    'Fallback Font': '后备字形',
    'Size': '大小',
    'Style': '风格',
    'Normal': '普通',
    'Bold': '粗体',
    'Italic': '斜体',
    'Align': '对齐',
    'Left': '左',
    'Center': '中',
    'Right': '右',
    'Color': '颜色',
    'Shadow': '阴影',
    'Blur': '模糊',
    'Save successed': '保存成功',
    'At least select two items': '最少需要选中两项',
    'Not a group': '不是一个组合',
    'Enter text here...': '在此输入文字...',
    
    // crop
    'Crop': '裁选',
    'New': '新建',
    'Dup..': '重复',
    'Del': '删除',
    'Re-Edit': '回到编辑',
    'Combine Crops': '合并裁选',
    'Density': '浓度',
    'Brightness': '亮度',
    'Saturation': '饱和度',
    'Start': '开始',
    'Please select one crop first.': '请先选择裁选框',
    'Get crop data error.': '获取裁选数据失败',
    'Loading, please try later.': '正在加载，请稍后再试',
    'Upload prepare failed.': '上传準备失败',
    'Upload done, sync failed.': '上传完成，同步出错',
    'Convert': '转换',
    'Send': '发送',
    'Successed': '成功',
    
    // setting
    'Global Density': '全局浓度',
    'Color Calibration': '色彩校準',
    'Cyan': '青色',
    'Magenta': '品红',
    'Yellow': '黄色',
    'Direction': '方向',
    'Cartridge Type': '墨盒类型',
    'CMY': '青红黄',
    'CYM': '青黄红',
    'Display Unit': '显示单位',
    'Device Setting': '设备设置',
    'Drive Strength': '驱动强度',
    'Color Alignment': '颜色对齐',
    'Leading Space': '前置空白',
    'Buzzer': '蜂鸣器',
    'Default': '默认',
    'Configuration': '配置',
    'SSID': 'SSID 名称',
    'Password': '密码',
    'Channel': '通道',
    'Not allowed in the US': '不可在美国使用',
    'Japan only': '仅限日本',
    'Read Dev': '读设备',
    'Write Dev': '写设备',
    'Device Info': '设备信息',
    'APP Version': 'APP 版本',
    'FW Version': '固件 版本',
    'DEV ID': '设备 ID',
    'Sensor IQC': '传感器 IQC',
    'Certificate': '证书',
    'Link': '链接',
    'Firmware Update': '固件升级',
    'Last Firmware': '最新固件',
    'Refresh App': '刷新应用',
    'Read app_conf from device error': '读取 app_conf 出错',
    'Read conf from device error': '读取 conf 出错',
    'Write conf to device error': '写 conf 出错',
    'Write app_conf to device error': '写 app_conf 出错',
    'Write to device successed': '写入成功',
    'Read wifi conf from device error': '读取 Wi-Fi 配置出错',
    'SSID is empty!': 'SSID 不能为空！',
    'Passwd at least 8 char!': '密码最短 8 位！',
    'Write wifi conf to device error': '写 Wi-Fi 配置出错',
    'Write to device successed, reboot...': '写入成功，重启...',
    'Please select file first': '请先选择文件',
    'Upgrade successed, reboot...': '升级成功，重启...',
    'Upgrade failed': '升级失败',
    'Upload': '上传',
    
    // other
    'Err': '出错',
    'No space left': '无剩余空间'
};

let trans_jp = {
    // app
    'Menu': 'メニュー',
    'Home': 'ホーム',
    'Setting': '設定',
    'Switching APP to new version.': 'アプリを新バージョンに切替中',

    // home
    'Projects': 'プロジェクト',
    'Open': '開く',
    'New': '新規',
    'Print': '印刷',
    'Edit': '編集',
    'Duplicate': '複製',
    'Export': 'エクスポート',
    'Export (Secret)': '保護してエクスポート',
    'Delete': '削除',
    'Cancel': 'キャンセル',

    'Alert': '注意',
    "Can't export secret project as normal.": '保護されたプロジェクトを通常版としてはエクスポートできません',
    'OK': 'OK',
    'Format error': '形式エラー',
    'Import successed': 'インポート完了しました',

    // edit
    'Add Image': '画像を追加',
    'Add Text': '文字を追加',
    'User Fonts': 'ユーザーフォント',
    'Ratio 1:1': '比率 1:1',
    'Delete Item': 'アイテムを削除',
    'Move up': '上に移動',
    'Down': '下に移動',
    'Top': '最前面',
    'Bottom': '最背面',
    'Group': 'グループ',
    'Ungroup': 'グループ化解除',
    'Save': '保存',
    'Print Preview': '印刷プレビュー',
    'Opacity': '不透明度',
    'Add Font': 'フォントを追加',
    'Add Text': '文字を追加',
    'Font': 'フォント',
    'Fallback Font': 'フォールバックフォント',
    'Size': 'サイズ',
    'Style': 'スタイル',
    'Normal': '通常',
    'Bold': '太字',
    'Italic': 'イタリック',
    'Align': '配置',
    'Left': '左寄せ',
    'Center': '中央寄せ',
    'Right': '右寄せ',
    'Color': '色',
    'Shadow': '影',
    'Blur': 'ぼかし',
    'Save successed': '保存しました',
    'At least select two items': '2つ以上のアイテムを選んでください',
    'Not a group': 'グループではありません',
    'Enter text here...': 'ここに文字を入力...',

    // crop
    'Crop': 'クロップ',
    'New': '新規',
    'Dup..': '複製',
    'Del': '削除',
    'Re-Edit': '再編集',
    'Combine Crops': 'クロップを結合',
    'Density': '濃度',
    'Brightness': '明るさ',
    'Saturation': '彩度',
    'Start': '開始',
    'Please select one crop first.': 'クロップをまず選択してください',
    'Get crop data error.': 'クロップデータの取得エラー',
    'Loading, please try later.': '読み込み中、後でお試しください',
    'Upload prepare failed.': 'アップロード準備に失敗しました',
    'Upload done, sync failed.': 'アップロード完了、動機に失敗しました',
    'Convert': '変換',
    'Send': '送信',
    'Successed': '成功しました',

    // setting
    'Global Density': '濃度',
    'Color Calibration': '色のキャリブレーション',
    'Cyan': 'シアン',
    'Magenta': 'マゼンタ',
    'Yellow': 'イエロー',
    'Direction': '向き',
    'Cartridge Type': 'カートリッジの種類',
    'CMY': 'CMY',
    'CYM': 'CYM',
    'Display Unit': '表示単位',
    'Device Setting': '機器設定',
    'Drive Strength': 'ドライブ強度',
    'Color Alignment': '色の調整',
    'Leading Space': '先頭の空白',
    'Buzzer': '音を鳴らす',
    'Default': 'デフォルト',
    'Configuration': '設定',
    'SSID': 'SSID',
    'Password': 'パスワード',
    'Channel': 'チャンネル',
    'Not allowed in the US': 'アメリカでは許可されていません',
    'Japan only': '日本のみ',
    'Read Dev': '読み込み',
    'Write Dev': '書き込み',
    'Device Info': '機器情報',
    'APP Version': 'アプリバージョン',
    'FW Version': 'ファームウェアバージョン',
    'DEV ID': '機器 ID',
    'Sensor IQC': 'センサー IQC',
    'Certificate': '証明書',
    'Link': 'リンク',
    'Firmware Update': 'ファームウェア更新',
    'Last Firmware': '最新のファームウェア',
    'Refresh App': 'アプリの再読み込み',
    'Read app_conf from device error': '機器からの app_conf の読み込みエラー',
    'Read conf from device error': '機器からの conf の読み込みエラー',
    'Write conf to device error': '機器への conf の書き込みエラー',
    'Write app_conf to device error': '機器への app_conf の書き込みエラー',
    'Write to device successed': '機器へ書き込みました',
    'Read wifi conf from device error': '機器からの Wi-Fi 設定の読み込みエラー',
    'SSID is empty!': 'SSID が空です！',
    'Passwd at least 8 char!': 'パスワードは最低8文字です！',
    'Write wifi conf to device error': '機器への Wi-Fi 設定の書き込みエラー',
    'Write to device successed, reboot...': '書き込みました。再起動します...',
    'Please select file first': 'ファイルを選んでください',
    'Upgrade successed, reboot...': '更新しました。再起動します...',
    'Upgrade failed': '更新に失敗しました',
    'Upload': 'アップロード',

    // other
    'Err': 'エラー',
    'No space left': '空きがありません'
};

let lang = 'en';
if (navigator.language.startsWith('zh')) {
    lang = 'hk';
    if (navigator.language.includes('CN'))
        lang = 'cn';
}
if (navigator.language.includes('ja'))
    lang = 'jp';

function L(ori, mark=null) {
    if (lang == 'en')
        return ori;
    if (!mark)
        mark = ori;
    let ret = lang == 'hk' ? trans_hk[mark] : lang == 'jp' ? trans_jp[mark] : trans_cn[mark];
    return ret || ori;
}

export { L };
